// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7OXf1lvvP6zyE6Xlmn2bt8jqBsgRAWJ4',
    appId: '1:643544470647:web:63d04ad0a890995ff8e272',
    messagingSenderId: '643544470647',
    projectId: 'calorie-counter-app-bf67e',
    authDomain: 'calorie-counter-app-bf67e.firebaseapp.com',
    storageBucket: 'calorie-counter-app-bf67e.firebasestorage.app',
    measurementId: 'G-S7SY3DS7P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2RboKRYaLhxHAsHeMQ4S7ZIBd6ZUXXw',
    appId: '1:643544470647:android:5e5ad74aa1be076ef8e272',
    messagingSenderId: '643544470647',
    projectId: 'calorie-counter-app-bf67e',
    storageBucket: 'calorie-counter-app-bf67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiKK88mwcj2K93t46z_Hzg6ZvITU_1K0',
    appId: '1:643544470647:ios:8ec188e320e27311f8e272',
    messagingSenderId: '643544470647',
    projectId: 'calorie-counter-app-bf67e',
    storageBucket: 'calorie-counter-app-bf67e.firebasestorage.app',
    iosBundleId: 'com.example.calorieCounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiKK88mwcj2K93t46z_Hzg6ZvITU_1K0',
    appId: '1:643544470647:ios:8ec188e320e27311f8e272',
    messagingSenderId: '643544470647',
    projectId: 'calorie-counter-app-bf67e',
    storageBucket: 'calorie-counter-app-bf67e.firebasestorage.app',
    iosBundleId: 'com.example.calorieCounterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7OXf1lvvP6zyE6Xlmn2bt8jqBsgRAWJ4',
    appId: '1:643544470647:web:d3cbc360d8ca64a3f8e272',
    messagingSenderId: '643544470647',
    projectId: 'calorie-counter-app-bf67e',
    authDomain: 'calorie-counter-app-bf67e.firebaseapp.com',
    storageBucket: 'calorie-counter-app-bf67e.firebasestorage.app',
    measurementId: 'G-9XV0994P3T',
  );
}
